### ISSUE TITLE
python 3.4 compatibility?

### ISSUE THREAD

**Issue by Serpens66** [nlsdfnbch/bitfinex_wss#14]
Hi :)

for what python version is your code?
It seems 3.4 is not supported, I get:

    entry = (*data, ts,)
                    ^
SyntaxError: can use starred expression only as assignment target

Searching for this error shows that this is something that was fixed in 3.5, but not in 3.4.
What would be the 3.4 equivalent of it?

edit:
And a question: How exactly and where is the data stored? From your description it sounds like that somewhere a file with the orderbook information is stored. But where? And is it necessary? 
I would like to know where, so I can delete it after closing websocket connection. Or is this not necessary?

**Comment by nlsdfnbch** [comment]
The lib is developed for 3.5+, yes. 
The equivalent for the above entry would be:
`entry = tuple(data + [ts])`


A file should only be created if you use the `BtfxWssRaw` class - this subclass dumps all data as is onto the disk. 
If you use the `BtfxWss` class, data should be stored in the class's attributes: `tickers`, `books`, `raw_books`, `_trades`, and `candles`.

There are, however, a crap ton of bugs left to fix - I apologize for that, I just didnt have the time the past few months to upload a proper fix for them.
