### ISSUE TITLE
Authentication Not working

### ISSUE THREAD

**Issue by nlsdfnbch** [nlsdfnbch/bitfinex_wss#2]
While the basic sign method has been written, authentication isn't working as of now.

**Comment by zdavatz** [comment]
Ok let us know when it will be working. Thank you.

**Comment by stefan-j** [comment]
I'm doing this for authentication:

```
def authenticate(self):
     global secret_key, api_key
     nonce = str(int(time.time() * 1000000000))
     payload = 'AUTH' + nonce
     h = hmac.new( secret_key, payload, hashlib.sha384)
     signature = h.hexdigest()
 
     data = {'event': 'auth'
            ,'apiKey': api_key
            ,'authPayload': payload
            ,'authNonce': nonce
            ,'authSig': signature
            }
     self.send(json.dumps(data))
```

I'm using this for the V2 API, however I based it of the V1 API documentation, so it should work. You'll automatically get subscribed to the authenticated channels after this

**Comment by zdavatz** [comment]
ok, thank you!

**Comment by nlsdfnbch** [comment]
Cheers, mate! The client is written for V2, so your code should work. I simply wasn't sure if this is to be sent with every command intended for the auth channels. But that's cleared up now - I'll implement it in the next days.

**Comment by nlsdfnbch** [comment]
..just leaving this open until I commit the changes

**Comment by zdavatz** [comment]
this is how we do it in Ruby: https://github.com/zdavatz/rapflag
