### ISSUE TITLE
pls change the following line in classes.py : line 1089 

### ISSUE THREAD

**Issue by GenesisGupta** [nlsdfnbch/bitfinex_wss#9]
current line : date = time.strftime('%Y-%m-%d_%H:%M:%S')

new line : time.strftime('%Y-%m-%d_%H_%M_%S')

new line does not throw an error , old line does

**Comment by nlsdfnbch** [comment]
Could you specify your Python version and OS ?

**Comment by GenesisGupta** [comment]
I am using windows 64 bit , python 3.5.3

Regards,
Nitin Gupta
9731423808

**Comment by nlsdfnbch** [comment]
Any what error are you seeing? There should be an error message and a stacktrace ( a bunch of lines of code pointing to the source of the issue, usually in red).

So far, I cannot reproduce this.
`date = time.strftime('%Y-%m-%d_%H:%M:%S')`
does not cause any error at all on my setup.
